
exclude_paths:
- testapi/**/*
- docs/**/*
- modules/**/*
- es6shim.js
- app.js
- webpack.config.js
- package.json
engines:
  # ... CONFIG CONTENT ...
  duplication:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      Similar code:
        enabled: false
# ... CONFIG CONTENT ...
languages:
  JavaScript: true
