
exclude_paths:
- testapi/**/*
- docs/**/*
- modules/**/*
- es6shim.js
- app.js
- webpack.config.js
- package.json
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    checks:
      Similar code:
        enabled: false
languages:
  JavaScript: true
