engines:
  # ... CONFIG CONTENT ...
  eslint:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      eqeqeq:
        enabled: false
# ... CONFIG CONTENT ...
languages:
  JavaScript: true
exclude_paths:
- testapi/**/*
- docs/**/*
- es6shim.js
- app.js
- webpack.config.js
- package.json
