
// Auth
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SET_HEADER = 'AUTH_SET_HEADER';
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';

// I18N
export const I18N_ENABLE_FALLBACK_LOADING = 'I18N_ENABLE_FALLBACK_LOADING';
export const I18N_ADD_FALLBACKS = 'I18N_ADD_FALLBACKS';
export const I18N_PARSE_LANGUAGE = 'I18N_PARSE_LANGUAGE';

// Config
export const CONFIG_ADD_URLS = 'CONFIG_ADD_URLS';
export const CONFIG_REMOVE_FIRST_URL = 'CONFIG_REMOVE_FIRST_URL';
export const CONFIG_LOAD_ERROR = 'CONFIG_LOAD_ERROR';
export const CONFIG_SET_PAGE = 'CONFIG_SET_PAGE';
export const CONFIG_SET_ENDPOINTS = 'CONFIG_SET_ENDPOINTS';
export const CONFIG_LOADED = 'CONFIG_LOADED';
