export const SEND_CONTACT_REQUEST = 'SEND_CONTACT_REQUEST'
export const TOGGLE_CUSTOMER_SPECIFIC = 'TOGGLE_CUSTOMER_SPECIFIC'
export const SET_FORM_DATA = 'SET_FORM_DATA'
export const INCREASE_SEND_STATE = 'INCREASE_SEND_STATE'
